#!/bin/bash
SCRIPT_PATH="$(dirname "${BASH_SOURCE[0]}")"

source "$SCRIPT_PATH/src/upper_lower.sh"

usage(){
    local use_str="$SCRIPT_PATH/memer <ARG> \"<STRING>\"
    
    \t-h\thelp
    \t-u\tUpPeR LoWeR
    "
    echo -e "$use_str"
}

output="$(usage)"
if [ $# -gt 2 ]; then 
    echo -e "Illegal number of parameters\n$(usage)"
    exit 1
fi

while getopts hu: flag
	do  
	    case "${flag}" in
            h) output=$(usage);;
            u) output="$(upper_lower ${OPTARG})";;
	    esac
	done
    

echo "$output"
exit 0
