
name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Install memer
    - name: Install memer
      run: ./install.sh
    
    # Runs a single command using the runners shell
    - name: Run test
      run: ./test/test.sh
